// Code generated by ogen, DO NOT EDIT.

package orderv1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CancelOrder implements cancelOrder operation.
//
// Отменить заказ.
//
// POST /api/v1/orders/{order_uuid}/cancel
func (UnimplementedHandler) CancelOrder(ctx context.Context, params CancelOrderParams) (r CancelOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOrder implements createOrder operation.
//
// Создать заказ.
//
// POST /api/v1/orders
func (UnimplementedHandler) CreateOrder(ctx context.Context, req *CreateOrderRequest) (r CreateOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrderByUuid implements getOrderByUuid operation.
//
// Получить заказ по UUID.
//
// GET /api/v1/orders/{order_uuid}
func (UnimplementedHandler) GetOrderByUuid(ctx context.Context, params GetOrderByUuidParams) (r GetOrderByUuidRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PayOrder implements payOrder operation.
//
// Оплатить заказ.
//
// POST /api/v1/orders/{order_uuid}/pay
func (UnimplementedHandler) PayOrder(ctx context.Context, req *PayOrderRequest, params PayOrderParams) (r PayOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}
